import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Correct import paths (after moving CSS files to src/app/styles/)
import "./styles/vendor/animate.css";
import "./styles/vendor/bootstrap.min.css";
import "./styles/vendor/magnific-popup.css";
import "./styles/vendor/nice-select.css";
import "./styles/vendor/owl.theme.default.min.css";
import "./styles/vendor/slick.css";
import "./styles/vendor/woocommerce.css";
import "./styles/custom/style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* External CSS if needed */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* JS scripts loaded from public/js/ */}
        <script src="/js/vendor/jquery.min.js"></script>
        <script src="/js/vendor/popper.min.js"></script>
        <script src="/js/vendor/bootstrap.min.js"></script>
        <script src="/js/vendor/gmaps.min.js"></script>
        <script src="/js/vendor/jquery-plugins-collection.js"></script>

        {/* Custom JS */}
        <script src="/js/custom/main.js"></script>
      </body>
    </html>
  );
}
