// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Local Font Awesome (installed via npm)
import "@fortawesome/fontawesome-free/css/all.min.css";

// Vendor and custom CSS
import "flowbite";
import "./styles/vendor/animate.css";
import "./styles/vendor/bootstrap.min.css";
import "./styles/vendor/magnific-popup.css";
import "./styles/vendor/nice-select.css";
import "./styles/vendor/owl.theme.default.min.css";
import "./styles/vendor/slick.css";
import "./styles/vendor/woocommerce.css";
import "./styles/custom/style.css";

import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/icofont@1.0.1/icofont.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Main page content */}
        <main>{children}</main>

        {/* JS scripts loaded from public/js/ */}
        <Script src="/js/vendor/jquery.min.js" strategy="beforeInteractive" />
        <Script src="/js/vendor/popper.min.js" strategy="beforeInteractive" />
        <Script
          src="/js/vendor/bootstrap.min.js"
          strategy="beforeInteractive"
        />
        <Script src="/js/vendor/gmaps.min.js" strategy="lazyOnload" />
        <Script
          src="/js/vendor/jquery-plugins-collection.js"
          strategy="lazyOnload"
        />
        <Script src="/js/custom/main.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
